package com.fmcg.ecommerce.service.impl;

import com.fmcg.ecommerce.dto.account.SavedPaymentDto;
import com.fmcg.ecommerce.entity.SavedPayment;
import com.fmcg.ecommerce.entity.User;
import com.fmcg.ecommerce.exception.ResourceNotFoundException;
import com.fmcg.ecommerce.repository.SavedPaymentRepository;
import com.fmcg.ecommerce.repository.UserRepository;
import com.fmcg.ecommerce.service.SavedPaymentService;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.util.List;
import java.util.stream.Collectors;

@Service
@RequiredArgsConstructor
public class SavedPaymentServiceImpl implements SavedPaymentService {

    private final SavedPaymentRepository savedPaymentRepository;
    private final UserRepository userRepository;

    @Override
    @Transactional(readOnly = true)
    public List<SavedPaymentDto.Response> getSavedPayments(Long userId) {
        return savedPaymentRepository.findByUserId(userId).stream()
                .map(this::toResponse)
                .collect(Collectors.toList());
    }

    @Override
    @Transactional
    public SavedPaymentDto.Response savePaymentMethod(Long userId, SavedPaymentDto.Request request) {
        User user = userRepository.findById(userId)
                .orElseThrow(() -> new ResourceNotFoundException("User", userId));

        // In a real app, 'token' would be generated by Stripe/Razorpay on the frontend and validated here.
        // For generic implementation, we just save what the frontend sends.
        
        SavedPayment payment = SavedPayment.builder()
                .user(user)
                .type(request.getType())
                .provider(request.getProvider())
                .last4(request.getLast4())
                .upiId(request.getUpiId())
                .token(request.getToken())
                .isDefault(request.getIsDefault() != null ? request.getIsDefault() : false)
                .build();

        return toResponse(savedPaymentRepository.save(payment));
    }

    @Override
    @Transactional
    public void deletePaymentMethod(Long userId, Long paymentId) {
        SavedPayment payment = savedPaymentRepository.findByIdAndUserId(paymentId, userId)
                .orElseThrow(() -> new ResourceNotFoundException("Payment Method", paymentId));
        savedPaymentRepository.delete(payment);
    }

    private SavedPaymentDto.Response toResponse(SavedPayment payment) {
        return SavedPaymentDto.Response.builder()
                .id(payment.getId())
                .type(payment.getType())
                .provider(payment.getProvider())
                .last4(payment.getLast4())
                .upiId(payment.getUpiId())
                .isDefault(payment.getIsDefault())
                // Token is intentionally omitted to maintain PCI compliance and security on the frontend
                .build();
    }
}
