ALTER TABLE ab_tests ADD COLUMN public_id VARCHAR(36) UNIQUE;
UPDATE ab_tests SET public_id = CAST(gen_random_uuid() AS VARCHAR) WHERE public_id IS NULL;
ALTER TABLE addresses ADD COLUMN public_id VARCHAR(36) UNIQUE;
UPDATE addresses SET public_id = CAST(gen_random_uuid() AS VARCHAR) WHERE public_id IS NULL;
ALTER TABLE audit_logs ADD COLUMN public_id VARCHAR(36) UNIQUE;
UPDATE audit_logs SET public_id = CAST(gen_random_uuid() AS VARCHAR) WHERE public_id IS NULL;
ALTER TABLE auth_tokens ADD COLUMN public_id VARCHAR(36) UNIQUE;
UPDATE auth_tokens SET public_id = CAST(gen_random_uuid() AS VARCHAR) WHERE public_id IS NULL;
ALTER TABLE carts ADD COLUMN public_id VARCHAR(36) UNIQUE;
UPDATE carts SET public_id = CAST(gen_random_uuid() AS VARCHAR) WHERE public_id IS NULL;
ALTER TABLE cart_items ADD COLUMN public_id VARCHAR(36) UNIQUE;
UPDATE cart_items SET public_id = CAST(gen_random_uuid() AS VARCHAR) WHERE public_id IS NULL;
ALTER TABLE categories ADD COLUMN public_id VARCHAR(36) UNIQUE;
UPDATE categories SET public_id = CAST(gen_random_uuid() AS VARCHAR) WHERE public_id IS NULL;
ALTER TABLE coupons ADD COLUMN public_id VARCHAR(36) UNIQUE;
UPDATE coupons SET public_id = CAST(gen_random_uuid() AS VARCHAR) WHERE public_id IS NULL;
ALTER TABLE customer_notes ADD COLUMN public_id VARCHAR(36) UNIQUE;
UPDATE customer_notes SET public_id = CAST(gen_random_uuid() AS VARCHAR) WHERE public_id IS NULL;
ALTER TABLE customer_segments ADD COLUMN public_id VARCHAR(36) UNIQUE;
UPDATE customer_segments SET public_id = CAST(gen_random_uuid() AS VARCHAR) WHERE public_id IS NULL;
ALTER TABLE delivery_partners ADD COLUMN public_id VARCHAR(36) UNIQUE;
UPDATE delivery_partners SET public_id = CAST(gen_random_uuid() AS VARCHAR) WHERE public_id IS NULL;
ALTER TABLE loyalty_accounts ADD COLUMN public_id VARCHAR(36) UNIQUE;
UPDATE loyalty_accounts SET public_id = CAST(gen_random_uuid() AS VARCHAR) WHERE public_id IS NULL;
ALTER TABLE loyalty_transactions ADD COLUMN public_id VARCHAR(36) UNIQUE;
UPDATE loyalty_transactions SET public_id = CAST(gen_random_uuid() AS VARCHAR) WHERE public_id IS NULL;
ALTER TABLE marketing_campaigns ADD COLUMN public_id VARCHAR(36) UNIQUE;
UPDATE marketing_campaigns SET public_id = CAST(gen_random_uuid() AS VARCHAR) WHERE public_id IS NULL;
ALTER TABLE notifications ADD COLUMN public_id VARCHAR(36) UNIQUE;
UPDATE notifications SET public_id = CAST(gen_random_uuid() AS VARCHAR) WHERE public_id IS NULL;
ALTER TABLE orders ADD COLUMN public_id VARCHAR(36) UNIQUE;
UPDATE orders SET public_id = CAST(gen_random_uuid() AS VARCHAR) WHERE public_id IS NULL;
ALTER TABLE order_items ADD COLUMN public_id VARCHAR(36) UNIQUE;
UPDATE order_items SET public_id = CAST(gen_random_uuid() AS VARCHAR) WHERE public_id IS NULL;
ALTER TABLE order_status_history ADD COLUMN public_id VARCHAR(36) UNIQUE;
UPDATE order_status_history SET public_id = CAST(gen_random_uuid() AS VARCHAR) WHERE public_id IS NULL;
ALTER TABLE otp_sessions ADD COLUMN public_id VARCHAR(36) UNIQUE;
UPDATE otp_sessions SET public_id = CAST(gen_random_uuid() AS VARCHAR) WHERE public_id IS NULL;
ALTER TABLE products ADD COLUMN public_id VARCHAR(36) UNIQUE;
UPDATE products SET public_id = CAST(gen_random_uuid() AS VARCHAR) WHERE public_id IS NULL;
ALTER TABLE product_images ADD COLUMN public_id VARCHAR(36) UNIQUE;
UPDATE product_images SET public_id = CAST(gen_random_uuid() AS VARCHAR) WHERE public_id IS NULL;
ALTER TABLE product_seo ADD COLUMN public_id VARCHAR(36) UNIQUE;
UPDATE product_seo SET public_id = CAST(gen_random_uuid() AS VARCHAR) WHERE public_id IS NULL;
ALTER TABLE promotions ADD COLUMN public_id VARCHAR(36) UNIQUE;
UPDATE promotions SET public_id = CAST(gen_random_uuid() AS VARCHAR) WHERE public_id IS NULL;
ALTER TABLE stock_movements ADD COLUMN public_id VARCHAR(36) UNIQUE;
UPDATE stock_movements SET public_id = CAST(gen_random_uuid() AS VARCHAR) WHERE public_id IS NULL;
ALTER TABLE stock_transfers ADD COLUMN public_id VARCHAR(36) UNIQUE;
UPDATE stock_transfers SET public_id = CAST(gen_random_uuid() AS VARCHAR) WHERE public_id IS NULL;
ALTER TABLE support_tickets ADD COLUMN public_id VARCHAR(36) UNIQUE;
UPDATE support_tickets SET public_id = CAST(gen_random_uuid() AS VARCHAR) WHERE public_id IS NULL;
ALTER TABLE users ADD COLUMN public_id VARCHAR(36) UNIQUE;
UPDATE users SET public_id = CAST(gen_random_uuid() AS VARCHAR) WHERE public_id IS NULL;
ALTER TABLE vendors ADD COLUMN public_id VARCHAR(36) UNIQUE;
UPDATE vendors SET public_id = CAST(gen_random_uuid() AS VARCHAR) WHERE public_id IS NULL;
ALTER TABLE warehouses ADD COLUMN public_id VARCHAR(36) UNIQUE;
UPDATE warehouses SET public_id = CAST(gen_random_uuid() AS VARCHAR) WHERE public_id IS NULL;

